### ISSUE TITLE
JaCoCo destination file is locked for too long on Windows

### ISSUE THREAD

**Issue by tlinkowski** [koral--/jacoco-gradle-testkit-plugin#9]
Hi, thanks a lot for your plugin!

I applied it, and it works just fine on Linux:
https://travis-ci.com/tlinkowski/tlinkowski-superpom/builds/118715882

# Problem

However, the build fails on Windows with the following message:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	[...]
Caused by: org.gradle.api.UncheckedIOException: Failed to create MD5 hash for file content.
	at org.gradle.internal.hash.DefaultStreamHasher.hash(DefaultStreamHasher.java:37)
	[...]
Caused by: java.io.IOException: Proces nie może uzyskać dostępu do pliku, ponieważ inny proces zablokował jego część
	at org.gradle.internal.hash.DefaultStreamHasher.doHash(DefaultStreamHasher.java:52)
	[...]
```

After investigating this, I found out that:
- the error is triggered for file `build/jacoco/test.exec`
- the error is triggered because Gradle needs to hash this file as an *output* of the `test` task
- the file is locked by the [JaCoCo agent](https://www.jacoco.org/jacoco/trunk/doc/agent.html) (the file is its `destfile`)
- the process that holds a lock to this file is the Gradle Daemon spawned by [`GradleRunner`](https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/GradleRunner.html) (which is instrumented to run with the JaCoCo agent)

# Solution

It took me quite a long time to figure out a workaround for this so I'd like to share it. It turns out it's enough to just wait some time at the end of the `test` task for the daemon to terminate.

Here's how I did it in my project (Kotlin DSL):
https://github.com/tlinkowski/tlinkowski-superpom/blob/e1b0d48a18f43980e609ad07b2d9f43afb75fad5/gradle/workAroundJacocoGradleTestKitIssueOnWindows.gradle.kts#L22-L40

**Comment by koral--** [comment]
Hi, thanks for the report.
Could you create a failing test which is reproducible on CI? This repo uses AppVeyor with Windows machines.

**Comment by tlinkowski** [comment]
Sure - will try to submit a PR within a couple of days.

**Comment by dgeissl** [comment]
I've stumbeled across this too, but solved it temporarily by using another jacoco destination file.
But now after some time - after upgrading to gradle 6.8.1 I've had this issue again, but this time that the reporting task could not find the exec file. Seems that the timing got longer and it even started failing on linux containers.

My groovy solution looks like this:
```groovy
def functionalTestTask = tasks.register('functionalTest', Test) {
            description = 'Runs the functional tests.'
            group = 'verification'
            dependsOn 'pluginUnderTestMetadata'

            testClassesDirs = sourceSets.functionalTest.output.classesDirs
            classpath = sourceSets.functionalTest.runtimeClasspath

            doLast {
                // https://github.com/koral--/jacoco-gradle-testkit-plugin/issues/9
                def jacocoReportFile = extensions.getByType(JacocoTaskExtension).destinationFile
                def retryCount = 0
                while((!jacocoReportFile.exists() || !jacocoReportFile.renameTo(jacocoReportFile)) && retryCount < 100){
                    retryCount++
                    println "Waiting for testkit.exec to be released ($retryCount)"
                    Thread.sleep(100)
                }
            }
        }
```

**Comment by Vampire** [comment]
I just get a read lock on the destination file as last action of the respective test task, works fine so far:
```kts
doLast {
    // wait for the read lock on the file, otherwise the daemon might still
    // have the write lock and Gradle complains that it cannot snapshot
    // the file as output of this task and as input of the report task
    FileChannel.open(the<JacocoTaskExtension>().destinationFile!!.toPath(), READ).use {
        it.lock(0, Long.MAX_VALUE, true).release()
    }
}
```

**Comment by Vampire** [comment]
Ok, it not fully works as it still happens occasionally that then this read lock is granted before some of the write locks of the started daemons.

So I now changed it a bit.
I still request the read lock on the file to be extra sure, but I changed the agent string to include the options `dumponexit=false,jmx=true`.

And then in the settings script of the projects under test I always add
```kts
import java.lang.management.ManagementFactory
import javax.management.ObjectName

abstract class JacocoDumper : BuildService<BuildServiceParameters.None>, AutoCloseable {
    override fun close() {
        val mBeanServer = ManagementFactory.getPlatformMBeanServer()
        val jacoco = ObjectName.getInstance("org.jacoco:type=Runtime")
        if (mBeanServer.isRegistered(jacoco)) {
            mBeanServer.invoke(jacoco, "dump", arrayOf(true), arrayOf("boolean"))
        }
    }
}
val jacocoDumper = gradle.sharedServices.registerIfAbsent("jacocoDumper", JacocoDumper::class) {}
jacocoDumper.get()
gradle.allprojects {
    tasks.configureEach {
        usesService(jacocoDumper)
    }
}
```
Now the writing of the JaCoCo data is done at the end of the build still within the SUT build run, so definitely before the file is then accessed by the outer build.
I think this should workout better.

**Comment by Vampire** [comment]
Or if you want it a bit more object-oriented
```groovy
...
    .withPluginClasspath()
    .with { it.withPluginClasspath(it.pluginClasspath + new File(jacocoAgentJar)) }
```
and then
```kts
import java.lang.management.ManagementFactory
import javax.management.JMX.newMBeanProxy
import javax.management.ObjectName
import org.jacoco.agent.rt.IAgent
[...]
        val mBeanServer = ManagementFactory.getPlatformMBeanServer()
        val jacoco = ObjectName.getInstance("org.jacoco:type=Runtime")
        if (mBeanServer.isRegistered(jacoco)) {
            newMBeanProxy(mBeanServer, jacoco, IAgent::class.java).dump(true)
        }
[...]
```
